const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');

// =============================================================================
// regression.spec.js — Howard D8 Multisite Visual Regression Tests
// =============================================================================
//
// HOW IT WORKS
//   This spec is driven by sites.json generated by regression_test.sh.
//   Each site gets one test. The test name is the domain only (never the env)
//   so Playwright uses the same snapshot file whether you are capturing a
//   baseline from prod or comparing dev/test against it.
//
//   Baseline capture (prod → snapshots):
//     HAL_TARGET_ENV=prod npx playwright test --update-snapshots
//
//   Comparison run (dev vs prod baseline):
//     HAL_TARGET_ENV=dev npx playwright test
//
// LOGIN SUPPORT
//   To test authenticated pages, add a "login" block to a site entry in
//   sites.json. The script regenerates sites.json each run, so add the block
//   after the script writes it, or maintain a hand-edited copy.
//
//   Example:
//     "login": {
//       "path": "/user/login",
//       "username_selector": "#edit-name",
//       "password_selector": "#edit-pass",
//       "submit_selector": "#edit-submit",
//       "username": "your.user@howard.edu",
//       "password": "yourpassword"
//     }
//
// DIFF TOLERANCE
//   maxDiffPixelRatio: 0.02 — up to 2% of total pixels may differ before
//   a test fails. Dynamic content (rotating banners, timestamps, etc.) may
//   require raising this value or masking regions. See Playwright docs:
//   https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1
//
// =============================================================================

const sitesFile  = path.join(__dirname, '..', 'sites.json');
const appName    = process.env.HAL_APP_NAME || 'unknown';
const snapshotOs = process.platform; // 'darwin' | 'linux' | 'win32'

// Bail early with a clear message rather than a cryptic Playwright error.
if (!fs.existsSync(sitesFile)) {
  throw new Error(
    'sites.json not found. Run regression_test.sh first to generate it.'
  );
}

const sites = JSON.parse(fs.readFileSync(sitesFile, 'utf8'));

// HAL_TARGET_ENV: which environment to screenshot this run (prod | dev | test).
// HAL_SHIELD_USER / HAL_SHIELD_PASS: HTTP Basic Auth credentials for shielded
// environments. Defaults to huweb:huweb (standard Acquia Howard setup).
const targetEnv   = process.env.HAL_TARGET_ENV   || 'prod';
const shieldUser  = process.env.HAL_SHIELD_USER  || 'huweb';
const shieldPass  = process.env.HAL_SHIELD_PASS  || 'huweb';
const isShielded  = targetEnv !== 'prod';
const baselineEnv = process.env.HAL_BASELINE_ENV || 'prod';

for (const site of sites) {
  const url = site[`${targetEnv}_url`];

  // Skip sites that don't have a URL for the requested environment.
  if (!url) continue;

  // Test name is the domain only — NOT the environment — so the Playwright
  // snapshot filename stays consistent between baseline and comparison runs.
  test(site.domain, async ({ browser }) => {

    // --- HTTP Basic Auth (Shield) ---
    // Dev and test environments are gated by the Drupal Shield module.
    // We inject credentials at the browser context level so every request
    // within this test (redirects, assets) passes authentication.
    const context = isShielded
      ? await browser.newContext({
          ignoreHTTPSErrors: true,
          httpCredentials: { username: shieldUser, password: shieldPass },
        })
      : await browser.newContext({ ignoreHTTPSErrors: true });

    const testPage = await context.newPage();

    try {
      // --- Optional Drupal login ---
      // If a login block is present, authenticate before navigating to the
      // page under test. Useful for comparing authenticated page states.
      if (site.login) {
        const { path: loginPath, username_selector, password_selector,
                submit_selector, username, password } = site.login;

        await testPage.goto(`${url}${loginPath}`, { waitUntil: 'networkidle' });
        await testPage.fill(username_selector, username);
        await testPage.fill(password_selector, password);
        await testPage.click(submit_selector);
        await testPage.waitForLoadState('networkidle');
      }

      // --- Navigate to the site homepage ---
      await testPage.goto(url, { waitUntil: 'networkidle', timeout: 30000 });

      // Brief settle pause for lazy-loaded images and CSS transitions.
      await testPage.waitForTimeout(1000);

      // Freeze JS timers (carousels, counters, rotating banners) so the page
      // is static when we screenshot. clearTimeout/clearInterval stops all
      // pending and repeating timers that would otherwise cause the screenshot
      // stability check to fail with "Failed to take two consecutive stable
      // screenshots."
      await testPage.evaluate(() => {
        const maxId = setTimeout(() => {}, 0);
        for (let i = 0; i <= maxId; i++) {
          clearTimeout(i);
          clearInterval(i);
        }
        // Pause any requestAnimationFrame-driven animations.
        window._halRafId = window.requestAnimationFrame;
        window.requestAnimationFrame = () => {};
        // Pause all video/audio elements so autoplaying media doesn't change
        // frames between Playwright's stability screenshots.
        document.querySelectorAll('video, audio').forEach(el => {
          try { el.pause(); } catch (e) {}
        });
      });

      // Extra CSS to ensure animation states are frozen even for libraries
      // that drive animations through inline style transitions.
      await testPage.addStyleTag({ content: `
        *, *::before, *::after {
          animation-play-state: paused !important;
          transition-duration: 0s !important;
          transition-delay: 0s !important;
        }
      ` });

      // Short additional settle after freezing to let any in-flight layout
      // reflows complete before we capture.
      await testPage.waitForTimeout(500);

      // --- Save actual screenshot for the side-by-side comparison report ---
      // Written to playwright/screenshots/<appName>/ — outside playwright-report/
      // so it is NOT wiped when the HTML reporter clears playwright-report/ at onEnd.
      const actualShot = await testPage.screenshot({ fullPage: true, animations: 'disabled' });
      const screenshotDir = path.join(__dirname, '..', 'screenshots', appName);
      fs.mkdirSync(screenshotDir, { recursive: true });
      fs.writeFileSync(path.join(screenshotDir, `${site.domain}-actual.png`), actualShot);

      // --- Visual snapshot comparison ---
      // Snapshot filename = domain + Playwright's auto-appended project/OS suffix.
      // e.g. admission.howard.edu-chromium-darwin.png
      //
      // On --update-snapshots runs this writes/overwrites the baseline.
      // On normal runs this compares against the stored baseline and fails
      // if the pixel diff exceeds maxDiffPixelRatio.
      await expect(testPage).toHaveScreenshot(`${site.domain}.png`, {
        fullPage: true,
        animations: 'disabled',
        // Allow up to 2% of pixels to differ. Raise if dynamic content
        // (carousels, live dates) causes false positives on your sites.
        maxDiffPixelRatio: 0.02,
        // Per-pixel color difference threshold (0–1). 0.2 tolerates minor
        // anti-aliasing and font rendering differences across environments.
        threshold: 0.2,
        // Extended stability timeout — gives Playwright more time to confirm
        // the page is static after timer/animation freezing above.
        timeout: 15000,
      });

    } finally {
      await context.close();
    }
  });
}
